name: instagram_clone
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Cupertino Icons
  cupertino_icons: ^0.1.3
  # Stacked
  stacked: ^1.6.0
  # third-party services
  stacked_services: ^0.4.4+1
  # navigation
  auto_route: ^0.5.0
  # inversion of control
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  # Flutter Spinkit
  flutter_spinkit: ^4.1.2+1
  # Logger
  logger: ^0.9.1

  # firebase stuff
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.15
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6

  firebase_auth_web: ^0.1.3+1
  cloud_firestore_web: ^0.1.1+2

  # media related
  flutter_image_compress: ^0.6.8
  cached_network_image: ^2.2.0+1
  image_picker: ^0.6.2+3
  image_cropper: ^1.1.1

  # misc
  uuid: ^2.1.0
  path_provider: ^1.6.11
  google_fonts: ^1.1.0
  animator: ^1.0.0+3
  intl: ^0.16.1
  shimmer: ^1.1.1
  responsive_builder: ^0.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  build_runner: ^1.10.0
  auto_route_generator: ^0.5.0
  injectable_generator: ^0.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/placeholders/user_placeholder.png

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
